<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/createfile/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.createfile.'), function () {

Route::get('createfiles', ['as'=> 'createfiles.index', 'uses' => 'Createfile\CreatefileController@index']);
Route::post('createfiles', ['as'=> 'createfiles.store', 'uses' => 'Createfile\CreatefileController@store']);
Route::get('createfiles/create', ['as'=> 'createfiles.create', 'uses' => 'Createfile\CreatefileController@create']);
Route::put('createfiles/{createfiles}', ['as'=> 'createfiles.update', 'uses' => 'Createfile\CreatefileController@update']);
Route::patch('createfiles/{createfiles}', ['as'=> 'createfiles.update', 'uses' => 'Createfile\CreatefileController@update']);
Route::get('createfiles/{id}/delete', ['as' => 'createfiles.delete', 'uses' => 'Createfile\CreatefileController@getDelete']);
Route::get('createfiles/{id}/confirm-delete', ['as' => 'createfiles.confirm-delete', 'uses' => 'Createfile\CreatefileController@getModalDelete']);
Route::get('createfiles/{createfiles}', ['as'=> 'createfiles.show', 'uses' => 'Createfile\CreatefileController@show']);
Route::get('createfiles/{createfiles}/edit', ['as'=> 'createfiles.edit', 'uses' => 'Createfile\CreatefileController@edit']);

});
